# Generated by Django 4.1.13 on 2025-01-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_genre_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ["id"]},
        ),
    ]
