# Generated by Django 5.1.4 on 2025-01-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_actor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="cinema.actor"),
        ),
    ]
